name: Build and Run API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dotnet-ci:
    permissions:
      contents: read
    uses: nate-demo/actions/.github/workflows/dotnet-ci.yml@main
    secrets: inherit
